backend:
  name: github
  repo: leonism/all-things-digital
  branch: main
  base_url: https://all-things-digital.pages.dev
  auth_endpoint: api/auth # This should match the path to your Cloudflare Function
  # auth_endpoint: api/callback # This should match the path to your Cloudflare Function
  # site_domain: all-things-digital.pages.dev # May be needed by some OAuth handlers
  # base_url: https://api.netlify.com
  # auth_endpoint: auth

media_folder: 'src/assets/img/uploads'
public_folder: '/assets/img/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/data/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Subtitle',
          name: 'subtitle',
          widget: 'string',
          required: false,
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'featuredImage',
          widget: 'object',
          fields:
            [
              { label: 'Source', name: 'src', widget: 'string' },
              { label: 'Alt Text', name: 'alt', widget: 'string' },
            ],
        }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: [] }
      - {
          label: 'Author',
          name: 'author',
          widget: 'object',
          fields:
            [
              { label: 'Name', name: 'name', widget: 'string' },
              { label: 'Image', name: 'image', widget: 'string' },
              {
                label: 'Link',
                name: 'link',
                widget: 'string',
                default: '/about',
              },
            ],
        }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: true,
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'src/content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Contact Page'
        name: 'contact'
        file: 'src/content/contact.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Settings'
    files:
      - label: 'Site Settings'
        name: 'site'
        file: 'src/data/site.json'
        fields:
          - { label: 'Site Title', name: 'title', widget: 'string' }
          - { label: 'Site Description', name: 'description', widget: 'text' }
          - { label: 'Site URL', name: 'url', widget: 'string' }
          - { label: 'Author Name', name: 'author', widget: 'string' }
          - {
              label: 'Social Media',
              name: 'social',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Twitter',
                    name: 'twitter',
                    widget: 'string',
                    required: false,
                  },
                  {
                    label: 'GitHub',
                    name: 'github',
                    widget: 'string',
                    required: false,
                  },
                  {
                    label: 'LinkedIn',
                    name: 'linkedin',
                    widget: 'string',
                    required: false,
                  },
                ],
            }
